repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: check-ast
    -   id: check-added-large-files
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: mixed-line-ending
    -   id: debug-statements
    -   id: requirements-txt-fixer
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-PyYAML, PyYAML, types-requests, requests, types-beautifulsoup4, beautifulsoup4, types-flask, Flask, schedule]
-   repo: https://github.com/jendrikseipp/vulture
    rev: 'v2.11'
    hooks:
    -   id: vulture
-   repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
    -   id: yamllint
-   repo: https://github.com/NtWriteCode/docker-pre-commit-universal
    rev: v4.0.2
    hooks:
    -   id: docker-compose-check
-   repo: https://github.com/AleksaC/hadolint-py
    rev: v2.12.1-beta
    hooks:
    -   id: hadolint
-   repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.73.0
    hooks:
    -   id: trufflehog
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
    -   id: bandit
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.1
    hooks:
    -   id: ruff
        args: [ --fix ]
    -   id: ruff-format
-   repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.359
    hooks:
    -   id: pyright
        additional_dependencies: [types-PyYAML, PyYAML, types-requests, requests, types-beautifulsoup4, beautifulsoup4, types-flask, Flask, schedule]
