repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: check-ast
    -   id: check-added-large-files
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: mixed-line-ending
    -   id: requirements-txt-fixer
-   repo: https://github.com/psf/black
    rev: 24.4.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-PyYAML, types-requests]
-   repo: https://github.com/asottile/dead
    rev: v1.5.2
    hooks:
    -   id: dead
-   repo: https://github.com/hakancelikdev/unimport
    rev: 1.2.1
    hooks:
    -   id: unimport
# -   repo: https://github.com/PyCQA/bandit
#     rev: 1.7.8
#     hooks:
#     -   id: bandit
