[tool.black]
line-length = 200
target-version = ['py310']

[tool.vulture]
ignore_decorators = ["@app.route", "@require_*"]
min_confidence = 80
paths = ["hardverapro_pp/", "cli.py"]
verbose = true

[tool.ruff]
line-length = 200
target-version = "py310"

[tool.ruff.lint]
select = ["ALL"]
ignore = ["D", "ANN101", "G004", "TRY002", "UP007"]
flake8-quotes.inline-quotes = "single"

[tool.ruff.lint.pylint]
max-args = 10

[tool.ruff.format]
quote-style = "single"
